// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "carvel.dev/secretgen-controller/pkg/apis/secretgen2/v1alpha1"
	scheme "carvel.dev/secretgen-controller/pkg/client2/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SecretTemplatesGetter has a method to return a SecretTemplateInterface.
// A group's client should implement this interface.
type SecretTemplatesGetter interface {
	SecretTemplates(namespace string) SecretTemplateInterface
}

// SecretTemplateInterface has methods to work with SecretTemplate resources.
type SecretTemplateInterface interface {
	Create(ctx context.Context, secretTemplate *v1alpha1.SecretTemplate, opts v1.CreateOptions) (*v1alpha1.SecretTemplate, error)
	Update(ctx context.Context, secretTemplate *v1alpha1.SecretTemplate, opts v1.UpdateOptions) (*v1alpha1.SecretTemplate, error)
	UpdateStatus(ctx context.Context, secretTemplate *v1alpha1.SecretTemplate, opts v1.UpdateOptions) (*v1alpha1.SecretTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SecretTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SecretTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretTemplate, err error)
	SecretTemplateExpansion
}

// secretTemplates implements SecretTemplateInterface
type secretTemplates struct {
	client rest.Interface
	ns     string
}

// newSecretTemplates returns a SecretTemplates
func newSecretTemplates(c *SecretgenV1alpha1Client, namespace string) *secretTemplates {
	return &secretTemplates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the secretTemplate, and returns the corresponding secretTemplate object, and an error if there is any.
func (c *secretTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SecretTemplate, err error) {
	result = &v1alpha1.SecretTemplate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secrettemplates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecretTemplates that match those selectors.
func (c *secretTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SecretTemplateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SecretTemplateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secrettemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested secretTemplates.
func (c *secretTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("secrettemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a secretTemplate and creates it.  Returns the server's representation of the secretTemplate, and an error, if there is any.
func (c *secretTemplates) Create(ctx context.Context, secretTemplate *v1alpha1.SecretTemplate, opts v1.CreateOptions) (result *v1alpha1.SecretTemplate, err error) {
	result = &v1alpha1.SecretTemplate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("secrettemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretTemplate).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a secretTemplate and updates it. Returns the server's representation of the secretTemplate, and an error, if there is any.
func (c *secretTemplates) Update(ctx context.Context, secretTemplate *v1alpha1.SecretTemplate, opts v1.UpdateOptions) (result *v1alpha1.SecretTemplate, err error) {
	result = &v1alpha1.SecretTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secrettemplates").
		Name(secretTemplate.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretTemplate).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *secretTemplates) UpdateStatus(ctx context.Context, secretTemplate *v1alpha1.SecretTemplate, opts v1.UpdateOptions) (result *v1alpha1.SecretTemplate, err error) {
	result = &v1alpha1.SecretTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secrettemplates").
		Name(secretTemplate.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretTemplate).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the secretTemplate and deletes it. Returns an error if one occurs.
func (c *secretTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secrettemplates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *secretTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secrettemplates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched secretTemplate.
func (c *secretTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretTemplate, err error) {
	result = &v1alpha1.SecretTemplate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("secrettemplates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
