// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/apis/secretgen2/v1alpha1"
	scheme "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/client2/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SecretExportsGetter has a method to return a SecretExportInterface.
// A group's client should implement this interface.
type SecretExportsGetter interface {
	SecretExports(namespace string) SecretExportInterface
}

// SecretExportInterface has methods to work with SecretExport resources.
type SecretExportInterface interface {
	Create(ctx context.Context, secretExport *v1alpha1.SecretExport, opts v1.CreateOptions) (*v1alpha1.SecretExport, error)
	Update(ctx context.Context, secretExport *v1alpha1.SecretExport, opts v1.UpdateOptions) (*v1alpha1.SecretExport, error)
	UpdateStatus(ctx context.Context, secretExport *v1alpha1.SecretExport, opts v1.UpdateOptions) (*v1alpha1.SecretExport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SecretExport, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SecretExportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretExport, err error)
	SecretExportExpansion
}

// secretExports implements SecretExportInterface
type secretExports struct {
	client rest.Interface
	ns     string
}

// newSecretExports returns a SecretExports
func newSecretExports(c *SecretgenV1alpha1Client, namespace string) *secretExports {
	return &secretExports{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the secretExport, and returns the corresponding secretExport object, and an error if there is any.
func (c *secretExports) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SecretExport, err error) {
	result = &v1alpha1.SecretExport{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretexports").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecretExports that match those selectors.
func (c *secretExports) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SecretExportList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SecretExportList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretexports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested secretExports.
func (c *secretExports) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("secretexports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a secretExport and creates it.  Returns the server's representation of the secretExport, and an error, if there is any.
func (c *secretExports) Create(ctx context.Context, secretExport *v1alpha1.SecretExport, opts v1.CreateOptions) (result *v1alpha1.SecretExport, err error) {
	result = &v1alpha1.SecretExport{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("secretexports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretExport).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a secretExport and updates it. Returns the server's representation of the secretExport, and an error, if there is any.
func (c *secretExports) Update(ctx context.Context, secretExport *v1alpha1.SecretExport, opts v1.UpdateOptions) (result *v1alpha1.SecretExport, err error) {
	result = &v1alpha1.SecretExport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretexports").
		Name(secretExport.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretExport).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *secretExports) UpdateStatus(ctx context.Context, secretExport *v1alpha1.SecretExport, opts v1.UpdateOptions) (result *v1alpha1.SecretExport, err error) {
	result = &v1alpha1.SecretExport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretexports").
		Name(secretExport.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretExport).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the secretExport and deletes it. Returns an error if one occurs.
func (c *secretExports) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretexports").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *secretExports) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretexports").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched secretExport.
func (c *secretExports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretExport, err error) {
	result = &v1alpha1.SecretExport{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("secretexports").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
