// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/apis/secretgen2/v1alpha1"
	scheme "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/client2/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SecretImportsGetter has a method to return a SecretImportInterface.
// A group's client should implement this interface.
type SecretImportsGetter interface {
	SecretImports(namespace string) SecretImportInterface
}

// SecretImportInterface has methods to work with SecretImport resources.
type SecretImportInterface interface {
	Create(ctx context.Context, secretImport *v1alpha1.SecretImport, opts v1.CreateOptions) (*v1alpha1.SecretImport, error)
	Update(ctx context.Context, secretImport *v1alpha1.SecretImport, opts v1.UpdateOptions) (*v1alpha1.SecretImport, error)
	UpdateStatus(ctx context.Context, secretImport *v1alpha1.SecretImport, opts v1.UpdateOptions) (*v1alpha1.SecretImport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SecretImport, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SecretImportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretImport, err error)
	SecretImportExpansion
}

// secretImports implements SecretImportInterface
type secretImports struct {
	client rest.Interface
	ns     string
}

// newSecretImports returns a SecretImports
func newSecretImports(c *SecretgenV1alpha1Client, namespace string) *secretImports {
	return &secretImports{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the secretImport, and returns the corresponding secretImport object, and an error if there is any.
func (c *secretImports) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SecretImport, err error) {
	result = &v1alpha1.SecretImport{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretimports").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecretImports that match those selectors.
func (c *secretImports) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SecretImportList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SecretImportList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretimports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested secretImports.
func (c *secretImports) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("secretimports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a secretImport and creates it.  Returns the server's representation of the secretImport, and an error, if there is any.
func (c *secretImports) Create(ctx context.Context, secretImport *v1alpha1.SecretImport, opts v1.CreateOptions) (result *v1alpha1.SecretImport, err error) {
	result = &v1alpha1.SecretImport{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("secretimports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretImport).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a secretImport and updates it. Returns the server's representation of the secretImport, and an error, if there is any.
func (c *secretImports) Update(ctx context.Context, secretImport *v1alpha1.SecretImport, opts v1.UpdateOptions) (result *v1alpha1.SecretImport, err error) {
	result = &v1alpha1.SecretImport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretimports").
		Name(secretImport.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretImport).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *secretImports) UpdateStatus(ctx context.Context, secretImport *v1alpha1.SecretImport, opts v1.UpdateOptions) (result *v1alpha1.SecretImport, err error) {
	result = &v1alpha1.SecretImport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretimports").
		Name(secretImport.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretImport).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the secretImport and deletes it. Returns an error if one occurs.
func (c *secretImports) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretimports").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *secretImports) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretimports").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched secretImport.
func (c *secretImports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretImport, err error) {
	result = &v1alpha1.SecretImport{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("secretimports").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
