// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SecretExportListerExpansion allows custom methods to be added to
// SecretExportLister.
type SecretExportListerExpansion interface{}

// SecretExportNamespaceListerExpansion allows custom methods to be added to
// SecretExportNamespaceLister.
type SecretExportNamespaceListerExpansion interface{}

// SecretImportListerExpansion allows custom methods to be added to
// SecretImportLister.
type SecretImportListerExpansion interface{}

// SecretImportNamespaceListerExpansion allows custom methods to be added to
// SecretImportNamespaceLister.
type SecretImportNamespaceListerExpansion interface{}

// SecretTemplateListerExpansion allows custom methods to be added to
// SecretTemplateLister.
type SecretTemplateListerExpansion interface{}

// SecretTemplateNamespaceListerExpansion allows custom methods to be added to
// SecretTemplateNamespaceLister.
type SecretTemplateNamespaceListerExpansion interface{}
