run:
  timeout: 5m
linters:
  enable:
    - goheader
    - revive
    - deadcode
    - unused
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 202[0-1]
    template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  new-from-rev: ae7b7b79a75756ae3cec92e8bb8c6bf0c4dab48e
