apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: "2022-07-21T18:41:22Z"
  name: sgc.carvel.dev.0.0.0
spec:
  refName: sgc.carvel.dev
  releasedAt: "2022-07-21T18:41:22Z"
  template:
    spec:
      deploy:
      - kapp: {}
      template:
      - ytt:
          paths:
          - config/package-bundle/config
          - config/dev
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: "2022-07-21T18:41:22Z"
  name: sgc.carvel.dev
spec:
  displayName: sgc
  longDescription: sgc.carvel.dev
  shortDescription: sgc.carvel.dev
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: "2022-07-21T18:41:22Z"
  name: sgc
spec:
  packageRef:
    refName: sgc.carvel.dev
  serviceAccountName: sgc-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
