#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("@ytt:yaml", "yaml")

#@ data.values.name or assert.fail("missing 'name' value")
#@ data.values.image or assert.fail("missing 'image' value")
#@ data.values.version or assert.fail("missing 'version' value")

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ data.values.name
spec:
  refName: #@ data.values.name
  version: #@ data.values.version
  releaseNotes: #@ "https://github.com/vmware-tanzu/carvel-secretgen-controller/releases/tag/" + data.values.version
  valuesSchema:
    openAPIv3: #@ yaml.decode(data.values.openapi)["components"]["schemas"]["dataValues"]
  licenses:
  - Apache 2.0
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: #@ data.values.image
      template:
        - ytt:
            paths:
              - 'config'
        - kbld:
            paths:
              - '.imgpkg/images.yml'
              - '-'
      deploy:
        - kapp: {}    
  