#@data/values-schema
---
#@schema/desc "The namespace in which to deploy secretgen-controller"
namespace: secretgen-controller
#@schema/desc "Whether to create namespace specified for secretgen-controller"
create_namespace: true

#@schema/desc "Configuration for secretgen-controller deployment"
#@overlay/match-child-defaults missing_ok=True
deployment:
  #@schema/desc "Update strategy of deployments, empty uses default strategy"
  updateStrategy: ""
  rollingUpdate:
    #@schema/desc "The maxUnavailable of rollingUpdate. Applied only if RollingUpdate is used as updateStrategy"
    maxUnavailable: 1
    #@schema/desc "The maxSurge of rollingUpdate. Applied only if RollingUpdate is used as updateStrategy"
    maxSurge: 0
  #@schema/type any=True
  #@schema/desc "NodeSelector configuration applied to all the deployments"
  nodeSelector: null