#!/bin/bash

set -ex

CGO_ENABLED=0 GOOS=linux go build -mod=vendor -ldflags="-X 'main.Version=develop' -buildid=" -trimpath -o controller-linux-amd64 ./cmd/controller/...

echo "# -- this file is autogenerated by rapid-deploy.sh from main Dockerfile and is not version controlled" > Dockerfile.dev

run_image_start=`cat Dockerfile | grep -n "\- run \-" | cut -d':' -f1`
tail -n +$run_image_start Dockerfile | \
  sed 's/COPY.*secretgen-controller/COPY controller-linux-amd64 secretgen-controller/' >> Dockerfile.dev

yq eval ".dev.rapid_deploy = true" -i config-deploy/values.yml

ytt -f config/ -f config-build/ -f config-deploy/ | kbld -f- | kapp deploy -a sg -f- -c -y

