// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/k14s/secretgen-controller/pkg/apis/secretgen/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecretExportApprovals implements SecretExportApprovalInterface
type FakeSecretExportApprovals struct {
	Fake *FakeSecretgenV1alpha1
	ns   string
}

var secretexportapprovalsResource = schema.GroupVersionResource{Group: "secretgen", Version: "v1alpha1", Resource: "secretexportapprovals"}

var secretexportapprovalsKind = schema.GroupVersionKind{Group: "secretgen", Version: "v1alpha1", Kind: "SecretExportApproval"}

// Get takes name of the secretExportApproval, and returns the corresponding secretExportApproval object, and an error if there is any.
func (c *FakeSecretExportApprovals) Get(name string, options v1.GetOptions) (result *v1alpha1.SecretExportApproval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(secretexportapprovalsResource, c.ns, name), &v1alpha1.SecretExportApproval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretExportApproval), err
}

// List takes label and field selectors, and returns the list of SecretExportApprovals that match those selectors.
func (c *FakeSecretExportApprovals) List(opts v1.ListOptions) (result *v1alpha1.SecretExportApprovalList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(secretexportapprovalsResource, secretexportapprovalsKind, c.ns, opts), &v1alpha1.SecretExportApprovalList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SecretExportApprovalList{ListMeta: obj.(*v1alpha1.SecretExportApprovalList).ListMeta}
	for _, item := range obj.(*v1alpha1.SecretExportApprovalList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested secretExportApprovals.
func (c *FakeSecretExportApprovals) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(secretexportapprovalsResource, c.ns, opts))

}

// Create takes the representation of a secretExportApproval and creates it.  Returns the server's representation of the secretExportApproval, and an error, if there is any.
func (c *FakeSecretExportApprovals) Create(secretExportApproval *v1alpha1.SecretExportApproval) (result *v1alpha1.SecretExportApproval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(secretexportapprovalsResource, c.ns, secretExportApproval), &v1alpha1.SecretExportApproval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretExportApproval), err
}

// Update takes the representation of a secretExportApproval and updates it. Returns the server's representation of the secretExportApproval, and an error, if there is any.
func (c *FakeSecretExportApprovals) Update(secretExportApproval *v1alpha1.SecretExportApproval) (result *v1alpha1.SecretExportApproval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(secretexportapprovalsResource, c.ns, secretExportApproval), &v1alpha1.SecretExportApproval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretExportApproval), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSecretExportApprovals) UpdateStatus(secretExportApproval *v1alpha1.SecretExportApproval) (*v1alpha1.SecretExportApproval, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(secretexportapprovalsResource, "status", c.ns, secretExportApproval), &v1alpha1.SecretExportApproval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretExportApproval), err
}

// Delete takes name of the secretExportApproval and deletes it. Returns an error if one occurs.
func (c *FakeSecretExportApprovals) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(secretexportapprovalsResource, c.ns, name), &v1alpha1.SecretExportApproval{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecretExportApprovals) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(secretexportapprovalsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SecretExportApprovalList{})
	return err
}

// Patch applies the patch and returns the patched secretExportApproval.
func (c *FakeSecretExportApprovals) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SecretExportApproval, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(secretexportapprovalsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SecretExportApproval{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretExportApproval), err
}
