// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/apis/secretgen/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSSHKeys implements SSHKeyInterface
type FakeSSHKeys struct {
	Fake *FakeSecretgenV1alpha1
	ns   string
}

var sshkeysResource = schema.GroupVersionResource{Group: "secretgen.k14s.io", Version: "v1alpha1", Resource: "sshkeys"}

var sshkeysKind = schema.GroupVersionKind{Group: "secretgen.k14s.io", Version: "v1alpha1", Kind: "SSHKey"}

// Get takes name of the sSHKey, and returns the corresponding sSHKey object, and an error if there is any.
func (c *FakeSSHKeys) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SSHKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sshkeysResource, c.ns, name), &v1alpha1.SSHKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SSHKey), err
}

// List takes label and field selectors, and returns the list of SSHKeys that match those selectors.
func (c *FakeSSHKeys) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SSHKeyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sshkeysResource, sshkeysKind, c.ns, opts), &v1alpha1.SSHKeyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SSHKeyList{ListMeta: obj.(*v1alpha1.SSHKeyList).ListMeta}
	for _, item := range obj.(*v1alpha1.SSHKeyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sSHKeys.
func (c *FakeSSHKeys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sshkeysResource, c.ns, opts))

}

// Create takes the representation of a sSHKey and creates it.  Returns the server's representation of the sSHKey, and an error, if there is any.
func (c *FakeSSHKeys) Create(ctx context.Context, sSHKey *v1alpha1.SSHKey, opts v1.CreateOptions) (result *v1alpha1.SSHKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sshkeysResource, c.ns, sSHKey), &v1alpha1.SSHKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SSHKey), err
}

// Update takes the representation of a sSHKey and updates it. Returns the server's representation of the sSHKey, and an error, if there is any.
func (c *FakeSSHKeys) Update(ctx context.Context, sSHKey *v1alpha1.SSHKey, opts v1.UpdateOptions) (result *v1alpha1.SSHKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sshkeysResource, c.ns, sSHKey), &v1alpha1.SSHKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SSHKey), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSSHKeys) UpdateStatus(ctx context.Context, sSHKey *v1alpha1.SSHKey, opts v1.UpdateOptions) (*v1alpha1.SSHKey, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sshkeysResource, "status", c.ns, sSHKey), &v1alpha1.SSHKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SSHKey), err
}

// Delete takes name of the sSHKey and deletes it. Returns an error if one occurs.
func (c *FakeSSHKeys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sshkeysResource, c.ns, name), &v1alpha1.SSHKey{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSSHKeys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sshkeysResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SSHKeyList{})
	return err
}

// Patch applies the patch and returns the patched sSHKey.
func (c *FakeSSHKeys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SSHKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sshkeysResource, c.ns, name, pt, data, subresources...), &v1alpha1.SSHKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SSHKey), err
}
