// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/apis/secretgen/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecretRequests implements SecretRequestInterface
type FakeSecretRequests struct {
	Fake *FakeSecretgenV1alpha1
	ns   string
}

var secretrequestsResource = schema.GroupVersionResource{Group: "secretgen.k14s.io", Version: "v1alpha1", Resource: "secretrequests"}

var secretrequestsKind = schema.GroupVersionKind{Group: "secretgen.k14s.io", Version: "v1alpha1", Kind: "SecretRequest"}

// Get takes name of the secretRequest, and returns the corresponding secretRequest object, and an error if there is any.
func (c *FakeSecretRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SecretRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(secretrequestsResource, c.ns, name), &v1alpha1.SecretRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretRequest), err
}

// List takes label and field selectors, and returns the list of SecretRequests that match those selectors.
func (c *FakeSecretRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SecretRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(secretrequestsResource, secretrequestsKind, c.ns, opts), &v1alpha1.SecretRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SecretRequestList{ListMeta: obj.(*v1alpha1.SecretRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.SecretRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested secretRequests.
func (c *FakeSecretRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(secretrequestsResource, c.ns, opts))

}

// Create takes the representation of a secretRequest and creates it.  Returns the server's representation of the secretRequest, and an error, if there is any.
func (c *FakeSecretRequests) Create(ctx context.Context, secretRequest *v1alpha1.SecretRequest, opts v1.CreateOptions) (result *v1alpha1.SecretRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(secretrequestsResource, c.ns, secretRequest), &v1alpha1.SecretRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretRequest), err
}

// Update takes the representation of a secretRequest and updates it. Returns the server's representation of the secretRequest, and an error, if there is any.
func (c *FakeSecretRequests) Update(ctx context.Context, secretRequest *v1alpha1.SecretRequest, opts v1.UpdateOptions) (result *v1alpha1.SecretRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(secretrequestsResource, c.ns, secretRequest), &v1alpha1.SecretRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSecretRequests) UpdateStatus(ctx context.Context, secretRequest *v1alpha1.SecretRequest, opts v1.UpdateOptions) (*v1alpha1.SecretRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(secretrequestsResource, "status", c.ns, secretRequest), &v1alpha1.SecretRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretRequest), err
}

// Delete takes name of the secretRequest and deletes it. Returns an error if one occurs.
func (c *FakeSecretRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(secretrequestsResource, c.ns, name), &v1alpha1.SecretRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecretRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(secretrequestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SecretRequestList{})
	return err
}

// Patch applies the patch and returns the patched secretRequest.
func (c *FakeSecretRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(secretrequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SecretRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretRequest), err
}
