// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/apis/secretgen/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRSAKeys implements RSAKeyInterface
type FakeRSAKeys struct {
	Fake *FakeSecretgenV1alpha1
	ns   string
}

var rsakeysResource = schema.GroupVersionResource{Group: "secretgen.k14s.io", Version: "v1alpha1", Resource: "rsakeys"}

var rsakeysKind = schema.GroupVersionKind{Group: "secretgen.k14s.io", Version: "v1alpha1", Kind: "RSAKey"}

// Get takes name of the rSAKey, and returns the corresponding rSAKey object, and an error if there is any.
func (c *FakeRSAKeys) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RSAKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rsakeysResource, c.ns, name), &v1alpha1.RSAKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RSAKey), err
}

// List takes label and field selectors, and returns the list of RSAKeys that match those selectors.
func (c *FakeRSAKeys) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RSAKeyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rsakeysResource, rsakeysKind, c.ns, opts), &v1alpha1.RSAKeyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RSAKeyList{ListMeta: obj.(*v1alpha1.RSAKeyList).ListMeta}
	for _, item := range obj.(*v1alpha1.RSAKeyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rSAKeys.
func (c *FakeRSAKeys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rsakeysResource, c.ns, opts))

}

// Create takes the representation of a rSAKey and creates it.  Returns the server's representation of the rSAKey, and an error, if there is any.
func (c *FakeRSAKeys) Create(ctx context.Context, rSAKey *v1alpha1.RSAKey, opts v1.CreateOptions) (result *v1alpha1.RSAKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rsakeysResource, c.ns, rSAKey), &v1alpha1.RSAKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RSAKey), err
}

// Update takes the representation of a rSAKey and updates it. Returns the server's representation of the rSAKey, and an error, if there is any.
func (c *FakeRSAKeys) Update(ctx context.Context, rSAKey *v1alpha1.RSAKey, opts v1.UpdateOptions) (result *v1alpha1.RSAKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rsakeysResource, c.ns, rSAKey), &v1alpha1.RSAKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RSAKey), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRSAKeys) UpdateStatus(ctx context.Context, rSAKey *v1alpha1.RSAKey, opts v1.UpdateOptions) (*v1alpha1.RSAKey, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rsakeysResource, "status", c.ns, rSAKey), &v1alpha1.RSAKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RSAKey), err
}

// Delete takes name of the rSAKey and deletes it. Returns an error if one occurs.
func (c *FakeRSAKeys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rsakeysResource, c.ns, name), &v1alpha1.RSAKey{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRSAKeys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rsakeysResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RSAKeyList{})
	return err
}

// Patch applies the patch and returns the patched rSAKey.
func (c *FakeRSAKeys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RSAKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rsakeysResource, c.ns, name, pt, data, subresources...), &v1alpha1.RSAKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RSAKey), err
}
