// Copyright 2021 VMware, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/apis/secretgen/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecretExports implements SecretExportInterface
type FakeSecretExports struct {
	Fake *FakeSecretgenV1alpha1
	ns   string
}

var secretexportsResource = schema.GroupVersionResource{Group: "secretgen", Version: "v1alpha1", Resource: "secretexports"}

var secretexportsKind = schema.GroupVersionKind{Group: "secretgen", Version: "v1alpha1", Kind: "SecretExport"}

// Get takes name of the secretExport, and returns the corresponding secretExport object, and an error if there is any.
func (c *FakeSecretExports) Get(name string, options v1.GetOptions) (result *v1alpha1.SecretExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(secretexportsResource, c.ns, name), &v1alpha1.SecretExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretExport), err
}

// List takes label and field selectors, and returns the list of SecretExports that match those selectors.
func (c *FakeSecretExports) List(opts v1.ListOptions) (result *v1alpha1.SecretExportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(secretexportsResource, secretexportsKind, c.ns, opts), &v1alpha1.SecretExportList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SecretExportList{ListMeta: obj.(*v1alpha1.SecretExportList).ListMeta}
	for _, item := range obj.(*v1alpha1.SecretExportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested secretExports.
func (c *FakeSecretExports) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(secretexportsResource, c.ns, opts))

}

// Create takes the representation of a secretExport and creates it.  Returns the server's representation of the secretExport, and an error, if there is any.
func (c *FakeSecretExports) Create(secretExport *v1alpha1.SecretExport) (result *v1alpha1.SecretExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(secretexportsResource, c.ns, secretExport), &v1alpha1.SecretExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretExport), err
}

// Update takes the representation of a secretExport and updates it. Returns the server's representation of the secretExport, and an error, if there is any.
func (c *FakeSecretExports) Update(secretExport *v1alpha1.SecretExport) (result *v1alpha1.SecretExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(secretexportsResource, c.ns, secretExport), &v1alpha1.SecretExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretExport), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSecretExports) UpdateStatus(secretExport *v1alpha1.SecretExport) (*v1alpha1.SecretExport, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(secretexportsResource, "status", c.ns, secretExport), &v1alpha1.SecretExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretExport), err
}

// Delete takes name of the secretExport and deletes it. Returns an error if one occurs.
func (c *FakeSecretExports) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(secretexportsResource, c.ns, name), &v1alpha1.SecretExport{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecretExports) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(secretexportsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SecretExportList{})
	return err
}

// Patch applies the patch and returns the patched secretExport.
func (c *FakeSecretExports) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SecretExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(secretexportsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SecretExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretExport), err
}
