// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/k14s/secretgen-controller/pkg/client/clientset/versioned/typed/secretgen/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSecretgenV1alpha1 struct {
	*testing.Fake
}

func (c *FakeSecretgenV1alpha1) Certificates(namespace string) v1alpha1.CertificateInterface {
	return &FakeCertificates{c, namespace}
}

func (c *FakeSecretgenV1alpha1) Passwords(namespace string) v1alpha1.PasswordInterface {
	return &FakePasswords{c, namespace}
}

func (c *FakeSecretgenV1alpha1) RSAKeys(namespace string) v1alpha1.RSAKeyInterface {
	return &FakeRSAKeys{c, namespace}
}

func (c *FakeSecretgenV1alpha1) SSHKeys(namespace string) v1alpha1.SSHKeyInterface {
	return &FakeSSHKeys{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSecretgenV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
