// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	secretgenv1alpha1 "github.com/k14s/secretgen-controller/pkg/apis/secretgen/v1alpha1"
	versioned "github.com/k14s/secretgen-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/k14s/secretgen-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/k14s/secretgen-controller/pkg/client/listers/secretgen/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SecretExportApprovalInformer provides access to a shared informer and lister for
// SecretExportApprovals.
type SecretExportApprovalInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SecretExportApprovalLister
}

type secretExportApprovalInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSecretExportApprovalInformer constructs a new informer for SecretExportApproval type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSecretExportApprovalInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSecretExportApprovalInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSecretExportApprovalInformer constructs a new informer for SecretExportApproval type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSecretExportApprovalInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretgenV1alpha1().SecretExportApprovals(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretgenV1alpha1().SecretExportApprovals(namespace).Watch(options)
			},
		},
		&secretgenv1alpha1.SecretExportApproval{},
		resyncPeriod,
		indexers,
	)
}

func (f *secretExportApprovalInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSecretExportApprovalInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *secretExportApprovalInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&secretgenv1alpha1.SecretExportApproval{}, f.defaultInformer)
}

func (f *secretExportApprovalInformer) Lister() v1alpha1.SecretExportApprovalLister {
	return v1alpha1.NewSecretExportApprovalLister(f.Informer().GetIndexer())
}
