#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretgen-controller
  namespace: #@ data.values.namespace
  annotations:
    secretgen-controller.carvel.dev/version: #@ data.values.secretgen_controller_version
spec:
  selector:
    matchLabels:
      app: secretgen-controller
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: secretgen-controller
    spec:
      serviceAccount: secretgen-controller-sa
      containers:
      - name: secretgen-controller
        image: secretgen-controller
        resources:
          requests:
            cpu: 120m
            memory: 100Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 2000
      securityContext:
        fsGroup: 3000
