#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretgen-controller
  namespace: #@ data.values.namespace
  annotations:
    secretgen-controller.carvel.dev/version: #@ data.values.secretgen_controller_version or assert.fail("'secretgen_controller_version' must be set")
spec:
  selector:
    matchLabels:
      app: secretgen-controller
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: secretgen-controller
    spec:
      serviceAccount: secretgen-controller-sa
      containers:
      - name: secretgen-controller
        image: secretgen-controller
        resources:
          requests:
            cpu: 120m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - all
