apiVersion: v1
kind: Namespace
metadata:
  name: user1-global
---
apiVersion: v1
kind: Namespace
metadata:
  name: user2
---
apiVersion: v1
kind: Namespace
metadata:
  name: user3
---
apiVersion: v1
kind: Namespace
metadata:
  name: user4

#! export registry creds to all namespaces
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: SecretExport
metadata:
  name: registry1-creds
  namespace: user1-global
spec:
  toNamespaces:
  - user2
  - user3
---
apiVersion: v1
kind: Secret
metadata:
  name: registry1-creds
  namespace: user1-global
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeTEiOnsiYXV0aCI6ImRYTmxjakU2Y0dGemN6RT0iLCJwYXNzd29yZCI6InBhc3MxIiwidXNlcm5hbWUiOiJ1c2VyMSJ9fX0=
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: SecretExport
metadata:
  name: registry2-creds
  namespace: user1-global
spec:
  toNamespaces:
  - user2
  - user3
---
apiVersion: v1
kind: Secret
metadata:
  name: registry2-creds
  namespace: user1-global
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeTIiOnsiYXV0aCI6ImRYTmxjakk2Y0dGemN6ST0iLCJwYXNzd29yZCI6InBhc3MyIiwidXNlcm5hbWUiOiJ1c2VyMiJ9fX0=

#! secret request in form of a secret
---
apiVersion: v1
kind: Secret
metadata:
  name: default-registry-creds
  namespace: user2
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "e30K"
---
apiVersion: v1
kind: Secret
metadata:
  name: default-registry-creds
  namespace: user3
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "e30K"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds-not-exported
  namespace: user4
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "e30K"
