apiVersion: v1
kind: Namespace
metadata:
  name: user1
---
apiVersion: v1
kind: Namespace
metadata:
  name: user2
---
apiVersion: v1
kind: Namespace
metadata:
  name: user3

#! export user-password secret from user1 to user2 namespace
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: user-password
  namespace: user1
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: user-password
  namespace: user1
spec:
  toNamespace: user2
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: user-password
  namespace: user2
spec:
  fromNamespace: user1

#! following export is for secret that does not exist
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: user-password-not-exist
  namespace: user1
spec:
  toNamespace: user1

#! following request is for export that does not exist
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: user-password-not-exist
  namespace: user2
spec:
  fromNamespace: user1

#! export user-password-multi secret from user1 to user2 namespace
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: user-password-multi
  namespace: user1
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: user-password-multi
  namespace: user1
spec:
  toNamespaces:
  - user2
  - user3
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: user-password-multi
  namespace: user2
spec:
  fromNamespace: user1
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: user-password-multi
  namespace: user3
spec:
  fromNamespace: user1

#! export user-password-multi secret from user1 to namespaces containing specific annotations
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: scoped-user-password-multi
  namespace: user1
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: scoped-user-password-multi
  namespace: user1
spec:
  toNamespaceAnnotation:
    field.cattle.io/projectId: "cluster1:project1"
  toNamespaceAnnotations:
    field.cattle.io/projectId: 
    - "cluster1:project2"
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: scoped-user-password-multi
  namespace: user2
  annotations:
    field.cattle.io/projectId: "cluster1:project1"
spec:
  fromNamespace: user1
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: scoped-user-password-multi
  namespace: user3
  annotations:
    field.cattle.io/projectId: "cluster1:project2"
spec:
  fromNamespace: user1


