// Copyright 2021 VMware, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type CertificateExpansion interface{}

type PasswordExpansion interface{}

type RSAKeyExpansion interface{}

type SSHKeyExpansion interface{}

type SecretExportExpansion interface{}

type SecretRequestExpansion interface{}
