// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type CertificateExpansion interface{}

type PasswordExpansion interface{}

type RSAKeyExpansion interface{}

type SSHKeyExpansion interface{}
