// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/apis/secretgen/v1alpha1"
	scheme "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RSAKeysGetter has a method to return a RSAKeyInterface.
// A group's client should implement this interface.
type RSAKeysGetter interface {
	RSAKeys(namespace string) RSAKeyInterface
}

// RSAKeyInterface has methods to work with RSAKey resources.
type RSAKeyInterface interface {
	Create(ctx context.Context, rSAKey *v1alpha1.RSAKey, opts v1.CreateOptions) (*v1alpha1.RSAKey, error)
	Update(ctx context.Context, rSAKey *v1alpha1.RSAKey, opts v1.UpdateOptions) (*v1alpha1.RSAKey, error)
	UpdateStatus(ctx context.Context, rSAKey *v1alpha1.RSAKey, opts v1.UpdateOptions) (*v1alpha1.RSAKey, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RSAKey, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RSAKeyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RSAKey, err error)
	RSAKeyExpansion
}

// rSAKeys implements RSAKeyInterface
type rSAKeys struct {
	client rest.Interface
	ns     string
}

// newRSAKeys returns a RSAKeys
func newRSAKeys(c *SecretgenV1alpha1Client, namespace string) *rSAKeys {
	return &rSAKeys{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rSAKey, and returns the corresponding rSAKey object, and an error if there is any.
func (c *rSAKeys) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RSAKey, err error) {
	result = &v1alpha1.RSAKey{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rsakeys").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RSAKeys that match those selectors.
func (c *rSAKeys) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RSAKeyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RSAKeyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rsakeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rSAKeys.
func (c *rSAKeys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rsakeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a rSAKey and creates it.  Returns the server's representation of the rSAKey, and an error, if there is any.
func (c *rSAKeys) Create(ctx context.Context, rSAKey *v1alpha1.RSAKey, opts v1.CreateOptions) (result *v1alpha1.RSAKey, err error) {
	result = &v1alpha1.RSAKey{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rsakeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rSAKey).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a rSAKey and updates it. Returns the server's representation of the rSAKey, and an error, if there is any.
func (c *rSAKeys) Update(ctx context.Context, rSAKey *v1alpha1.RSAKey, opts v1.UpdateOptions) (result *v1alpha1.RSAKey, err error) {
	result = &v1alpha1.RSAKey{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rsakeys").
		Name(rSAKey.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rSAKey).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *rSAKeys) UpdateStatus(ctx context.Context, rSAKey *v1alpha1.RSAKey, opts v1.UpdateOptions) (result *v1alpha1.RSAKey, err error) {
	result = &v1alpha1.RSAKey{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rsakeys").
		Name(rSAKey.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rSAKey).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the rSAKey and deletes it. Returns an error if one occurs.
func (c *rSAKeys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rsakeys").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rSAKeys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rsakeys").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched rSAKey.
func (c *rSAKeys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RSAKey, err error) {
	result = &v1alpha1.RSAKey{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rsakeys").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
