// Copyright 2021 VMware, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/apis/secretgen/v1alpha1"
	scheme "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RSAKeysGetter has a method to return a RSAKeyInterface.
// A group's client should implement this interface.
type RSAKeysGetter interface {
	RSAKeys(namespace string) RSAKeyInterface
}

// RSAKeyInterface has methods to work with RSAKey resources.
type RSAKeyInterface interface {
	Create(*v1alpha1.RSAKey) (*v1alpha1.RSAKey, error)
	Update(*v1alpha1.RSAKey) (*v1alpha1.RSAKey, error)
	UpdateStatus(*v1alpha1.RSAKey) (*v1alpha1.RSAKey, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RSAKey, error)
	List(opts v1.ListOptions) (*v1alpha1.RSAKeyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RSAKey, err error)
	RSAKeyExpansion
}

// rSAKeys implements RSAKeyInterface
type rSAKeys struct {
	client rest.Interface
	ns     string
}

// newRSAKeys returns a RSAKeys
func newRSAKeys(c *SecretgenV1alpha1Client, namespace string) *rSAKeys {
	return &rSAKeys{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rSAKey, and returns the corresponding rSAKey object, and an error if there is any.
func (c *rSAKeys) Get(name string, options v1.GetOptions) (result *v1alpha1.RSAKey, err error) {
	result = &v1alpha1.RSAKey{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rsakeys").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RSAKeys that match those selectors.
func (c *rSAKeys) List(opts v1.ListOptions) (result *v1alpha1.RSAKeyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RSAKeyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rsakeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rSAKeys.
func (c *rSAKeys) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rsakeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a rSAKey and creates it.  Returns the server's representation of the rSAKey, and an error, if there is any.
func (c *rSAKeys) Create(rSAKey *v1alpha1.RSAKey) (result *v1alpha1.RSAKey, err error) {
	result = &v1alpha1.RSAKey{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rsakeys").
		Body(rSAKey).
		Do().
		Into(result)
	return
}

// Update takes the representation of a rSAKey and updates it. Returns the server's representation of the rSAKey, and an error, if there is any.
func (c *rSAKeys) Update(rSAKey *v1alpha1.RSAKey) (result *v1alpha1.RSAKey, err error) {
	result = &v1alpha1.RSAKey{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rsakeys").
		Name(rSAKey.Name).
		Body(rSAKey).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *rSAKeys) UpdateStatus(rSAKey *v1alpha1.RSAKey) (result *v1alpha1.RSAKey, err error) {
	result = &v1alpha1.RSAKey{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rsakeys").
		Name(rSAKey.Name).
		SubResource("status").
		Body(rSAKey).
		Do().
		Into(result)
	return
}

// Delete takes name of the rSAKey and deletes it. Returns an error if one occurs.
func (c *rSAKeys) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rsakeys").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rSAKeys) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rsakeys").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched rSAKey.
func (c *rSAKeys) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RSAKey, err error) {
	result = &v1alpha1.RSAKey{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rsakeys").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
