// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/k14s/secretgen-controller/pkg/apis/secretgen/v1alpha1"
	scheme "github.com/k14s/secretgen-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SecretExportApprovalsGetter has a method to return a SecretExportApprovalInterface.
// A group's client should implement this interface.
type SecretExportApprovalsGetter interface {
	SecretExportApprovals(namespace string) SecretExportApprovalInterface
}

// SecretExportApprovalInterface has methods to work with SecretExportApproval resources.
type SecretExportApprovalInterface interface {
	Create(*v1alpha1.SecretExportApproval) (*v1alpha1.SecretExportApproval, error)
	Update(*v1alpha1.SecretExportApproval) (*v1alpha1.SecretExportApproval, error)
	UpdateStatus(*v1alpha1.SecretExportApproval) (*v1alpha1.SecretExportApproval, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SecretExportApproval, error)
	List(opts v1.ListOptions) (*v1alpha1.SecretExportApprovalList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SecretExportApproval, err error)
	SecretExportApprovalExpansion
}

// secretExportApprovals implements SecretExportApprovalInterface
type secretExportApprovals struct {
	client rest.Interface
	ns     string
}

// newSecretExportApprovals returns a SecretExportApprovals
func newSecretExportApprovals(c *SecretgenV1alpha1Client, namespace string) *secretExportApprovals {
	return &secretExportApprovals{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the secretExportApproval, and returns the corresponding secretExportApproval object, and an error if there is any.
func (c *secretExportApprovals) Get(name string, options v1.GetOptions) (result *v1alpha1.SecretExportApproval, err error) {
	result = &v1alpha1.SecretExportApproval{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretexportapprovals").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecretExportApprovals that match those selectors.
func (c *secretExportApprovals) List(opts v1.ListOptions) (result *v1alpha1.SecretExportApprovalList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SecretExportApprovalList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretexportapprovals").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested secretExportApprovals.
func (c *secretExportApprovals) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("secretexportapprovals").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a secretExportApproval and creates it.  Returns the server's representation of the secretExportApproval, and an error, if there is any.
func (c *secretExportApprovals) Create(secretExportApproval *v1alpha1.SecretExportApproval) (result *v1alpha1.SecretExportApproval, err error) {
	result = &v1alpha1.SecretExportApproval{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("secretexportapprovals").
		Body(secretExportApproval).
		Do().
		Into(result)
	return
}

// Update takes the representation of a secretExportApproval and updates it. Returns the server's representation of the secretExportApproval, and an error, if there is any.
func (c *secretExportApprovals) Update(secretExportApproval *v1alpha1.SecretExportApproval) (result *v1alpha1.SecretExportApproval, err error) {
	result = &v1alpha1.SecretExportApproval{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretexportapprovals").
		Name(secretExportApproval.Name).
		Body(secretExportApproval).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *secretExportApprovals) UpdateStatus(secretExportApproval *v1alpha1.SecretExportApproval) (result *v1alpha1.SecretExportApproval, err error) {
	result = &v1alpha1.SecretExportApproval{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretexportapprovals").
		Name(secretExportApproval.Name).
		SubResource("status").
		Body(secretExportApproval).
		Do().
		Into(result)
	return
}

// Delete takes name of the secretExportApproval and deletes it. Returns an error if one occurs.
func (c *secretExportApprovals) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretexportapprovals").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *secretExportApprovals) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretexportapprovals").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched secretExportApproval.
func (c *secretExportApprovals) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SecretExportApproval, err error) {
	result = &v1alpha1.SecretExportApproval{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("secretexportapprovals").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
