// Copyright 2021 VMware, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/apis/secretgen/v1alpha1"
	scheme "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SSHKeysGetter has a method to return a SSHKeyInterface.
// A group's client should implement this interface.
type SSHKeysGetter interface {
	SSHKeys(namespace string) SSHKeyInterface
}

// SSHKeyInterface has methods to work with SSHKey resources.
type SSHKeyInterface interface {
	Create(*v1alpha1.SSHKey) (*v1alpha1.SSHKey, error)
	Update(*v1alpha1.SSHKey) (*v1alpha1.SSHKey, error)
	UpdateStatus(*v1alpha1.SSHKey) (*v1alpha1.SSHKey, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SSHKey, error)
	List(opts v1.ListOptions) (*v1alpha1.SSHKeyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SSHKey, err error)
	SSHKeyExpansion
}

// sSHKeys implements SSHKeyInterface
type sSHKeys struct {
	client rest.Interface
	ns     string
}

// newSSHKeys returns a SSHKeys
func newSSHKeys(c *SecretgenV1alpha1Client, namespace string) *sSHKeys {
	return &sSHKeys{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sSHKey, and returns the corresponding sSHKey object, and an error if there is any.
func (c *sSHKeys) Get(name string, options v1.GetOptions) (result *v1alpha1.SSHKey, err error) {
	result = &v1alpha1.SSHKey{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sshkeys").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(context.Background()).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SSHKeys that match those selectors.
func (c *sSHKeys) List(opts v1.ListOptions) (result *v1alpha1.SSHKeyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SSHKeyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sshkeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(context.Background()).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sSHKeys.
func (c *sSHKeys) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sshkeys").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(context.Background())
}

// Create takes the representation of a sSHKey and creates it.  Returns the server's representation of the sSHKey, and an error, if there is any.
func (c *sSHKeys) Create(sSHKey *v1alpha1.SSHKey) (result *v1alpha1.SSHKey, err error) {
	result = &v1alpha1.SSHKey{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sshkeys").
		Body(sSHKey).
		Do(context.Background()).
		Into(result)
	return
}

// Update takes the representation of a sSHKey and updates it. Returns the server's representation of the sSHKey, and an error, if there is any.
func (c *sSHKeys) Update(sSHKey *v1alpha1.SSHKey) (result *v1alpha1.SSHKey, err error) {
	result = &v1alpha1.SSHKey{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sshkeys").
		Name(sSHKey.Name).
		Body(sSHKey).
		Do(context.Background()).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *sSHKeys) UpdateStatus(sSHKey *v1alpha1.SSHKey) (result *v1alpha1.SSHKey, err error) {
	result = &v1alpha1.SSHKey{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sshkeys").
		Name(sSHKey.Name).
		SubResource("status").
		Body(sSHKey).
		Do(context.Background()).
		Into(result)
	return
}

// Delete takes name of the sSHKey and deletes it. Returns an error if one occurs.
func (c *sSHKeys) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sshkeys").
		Name(name).
		Body(options).
		Do(context.Background()).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sSHKeys) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sshkeys").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do(context.Background()).
		Error()
}

// Patch applies the patch and returns the patched sSHKey.
func (c *sSHKeys) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SSHKey, err error) {
	result = &v1alpha1.SSHKey{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sshkeys").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do(context.Background()).
		Into(result)
	return
}
