#@ load("@ytt:overlay", "overlay")

#@overlay/remove
#@overlay/match by=overlay.subset({"kind": "Bundle"}), expects="0+"
---
#@overlay/remove
#@overlay/match by=overlay.subset({"kind": "ImagesLock"}), expects="0+"
---