// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "carvel.dev/secretgen-controller/pkg/apis/secretgen2/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecretImports implements SecretImportInterface
type FakeSecretImports struct {
	Fake *FakeSecretgenV1alpha1
	ns   string
}

var secretimportsResource = schema.GroupVersionResource{Group: "secretgen.carvel.dev", Version: "v1alpha1", Resource: "secretimports"}

var secretimportsKind = schema.GroupVersionKind{Group: "secretgen.carvel.dev", Version: "v1alpha1", Kind: "SecretImport"}

// Get takes name of the secretImport, and returns the corresponding secretImport object, and an error if there is any.
func (c *FakeSecretImports) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SecretImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(secretimportsResource, c.ns, name), &v1alpha1.SecretImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretImport), err
}

// List takes label and field selectors, and returns the list of SecretImports that match those selectors.
func (c *FakeSecretImports) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SecretImportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(secretimportsResource, secretimportsKind, c.ns, opts), &v1alpha1.SecretImportList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SecretImportList{ListMeta: obj.(*v1alpha1.SecretImportList).ListMeta}
	for _, item := range obj.(*v1alpha1.SecretImportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested secretImports.
func (c *FakeSecretImports) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(secretimportsResource, c.ns, opts))

}

// Create takes the representation of a secretImport and creates it.  Returns the server's representation of the secretImport, and an error, if there is any.
func (c *FakeSecretImports) Create(ctx context.Context, secretImport *v1alpha1.SecretImport, opts v1.CreateOptions) (result *v1alpha1.SecretImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(secretimportsResource, c.ns, secretImport), &v1alpha1.SecretImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretImport), err
}

// Update takes the representation of a secretImport and updates it. Returns the server's representation of the secretImport, and an error, if there is any.
func (c *FakeSecretImports) Update(ctx context.Context, secretImport *v1alpha1.SecretImport, opts v1.UpdateOptions) (result *v1alpha1.SecretImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(secretimportsResource, c.ns, secretImport), &v1alpha1.SecretImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretImport), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSecretImports) UpdateStatus(ctx context.Context, secretImport *v1alpha1.SecretImport, opts v1.UpdateOptions) (*v1alpha1.SecretImport, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(secretimportsResource, "status", c.ns, secretImport), &v1alpha1.SecretImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretImport), err
}

// Delete takes name of the secretImport and deletes it. Returns an error if one occurs.
func (c *FakeSecretImports) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(secretimportsResource, c.ns, name), &v1alpha1.SecretImport{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecretImports) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(secretimportsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SecretImportList{})
	return err
}

// Patch applies the patch and returns the patched secretImport.
func (c *FakeSecretImports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(secretimportsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SecretImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretImport), err
}
