// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "carvel.dev/secretgen-controller/pkg/client2/clientset/versioned/typed/secretgen2/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSecretgenV1alpha1 struct {
	*testing.Fake
}

func (c *FakeSecretgenV1alpha1) SecretExports(namespace string) v1alpha1.SecretExportInterface {
	return &FakeSecretExports{c, namespace}
}

func (c *FakeSecretgenV1alpha1) SecretImports(namespace string) v1alpha1.SecretImportInterface {
	return &FakeSecretImports{c, namespace}
}

func (c *FakeSecretgenV1alpha1) SecretTemplates(namespace string) v1alpha1.SecretTemplateInterface {
	return &FakeSecretTemplates{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSecretgenV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
