// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/carvel-secretgen-controller/pkg/apis/secretgen2/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecretTemplates implements SecretTemplateInterface
type FakeSecretTemplates struct {
	Fake *FakeSecretgenV1alpha1
	ns   string
}

var secrettemplatesResource = schema.GroupVersionResource{Group: "secretgen.carvel.dev", Version: "v1alpha1", Resource: "secrettemplates"}

var secrettemplatesKind = schema.GroupVersionKind{Group: "secretgen.carvel.dev", Version: "v1alpha1", Kind: "SecretTemplate"}

// Get takes name of the secretTemplate, and returns the corresponding secretTemplate object, and an error if there is any.
func (c *FakeSecretTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SecretTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(secrettemplatesResource, c.ns, name), &v1alpha1.SecretTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretTemplate), err
}

// List takes label and field selectors, and returns the list of SecretTemplates that match those selectors.
func (c *FakeSecretTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SecretTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(secrettemplatesResource, secrettemplatesKind, c.ns, opts), &v1alpha1.SecretTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SecretTemplateList{ListMeta: obj.(*v1alpha1.SecretTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.SecretTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested secretTemplates.
func (c *FakeSecretTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(secrettemplatesResource, c.ns, opts))

}

// Create takes the representation of a secretTemplate and creates it.  Returns the server's representation of the secretTemplate, and an error, if there is any.
func (c *FakeSecretTemplates) Create(ctx context.Context, secretTemplate *v1alpha1.SecretTemplate, opts v1.CreateOptions) (result *v1alpha1.SecretTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(secrettemplatesResource, c.ns, secretTemplate), &v1alpha1.SecretTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretTemplate), err
}

// Update takes the representation of a secretTemplate and updates it. Returns the server's representation of the secretTemplate, and an error, if there is any.
func (c *FakeSecretTemplates) Update(ctx context.Context, secretTemplate *v1alpha1.SecretTemplate, opts v1.UpdateOptions) (result *v1alpha1.SecretTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(secrettemplatesResource, c.ns, secretTemplate), &v1alpha1.SecretTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSecretTemplates) UpdateStatus(ctx context.Context, secretTemplate *v1alpha1.SecretTemplate, opts v1.UpdateOptions) (*v1alpha1.SecretTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(secrettemplatesResource, "status", c.ns, secretTemplate), &v1alpha1.SecretTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretTemplate), err
}

// Delete takes name of the secretTemplate and deletes it. Returns an error if one occurs.
func (c *FakeSecretTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(secrettemplatesResource, c.ns, name), &v1alpha1.SecretTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecretTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(secrettemplatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SecretTemplateList{})
	return err
}

// Patch applies the patch and returns the patched secretTemplate.
func (c *FakeSecretTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SecretTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(secrettemplatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.SecretTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretTemplate), err
}
