#@ load("@ytt:data", "data")

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: secretgen-controller
  path: .
  docker:
    build:
      #@ if data.values.dev.rapid_deploy:
      pull: false
      noCache: false
      file: Dockerfile.dev
      buildkit: true
      #@ elif data.values.dev.push_images:
      #! Always rebuild image
      pull: true
      noCache: true
      rawOptions: #@ ["--build-arg", "SGCTRL_VER="+data.values.dev.version]
      #@ end

#@ if/end data.values.dev.push_images:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: secretgen-controller
  newImage: #@ data.values.dev.image_repo
