#@data/values-schema
---
#@schema/desc "The name of secretgen-controller Package"
name: secretgen-controller.carvel.dev
#@schema/desc "The version of secretgen-controller Package"
version:
#@schema/desc "The image of secretgen-controller Package"
image:
