#@ load("@ytt:data", "data")
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: secretgen-controller
  path: .
  docker:
    build:
      pull: false
      noCache: false
      file: Dockerfile.dev
      buildkit: true

#@ if/end data.values.push_images:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: secretgen-controller
  newImage: #@ data.values.image_repo