// Copyright 2021 VMware, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CertificateListerExpansion allows custom methods to be added to
// CertificateLister.
type CertificateListerExpansion interface{}

// CertificateNamespaceListerExpansion allows custom methods to be added to
// CertificateNamespaceLister.
type CertificateNamespaceListerExpansion interface{}

// PasswordListerExpansion allows custom methods to be added to
// PasswordLister.
type PasswordListerExpansion interface{}

// PasswordNamespaceListerExpansion allows custom methods to be added to
// PasswordNamespaceLister.
type PasswordNamespaceListerExpansion interface{}

// RSAKeyListerExpansion allows custom methods to be added to
// RSAKeyLister.
type RSAKeyListerExpansion interface{}

// RSAKeyNamespaceListerExpansion allows custom methods to be added to
// RSAKeyNamespaceLister.
type RSAKeyNamespaceListerExpansion interface{}

// SSHKeyListerExpansion allows custom methods to be added to
// SSHKeyLister.
type SSHKeyListerExpansion interface{}

// SSHKeyNamespaceListerExpansion allows custom methods to be added to
// SSHKeyNamespaceLister.
type SSHKeyNamespaceListerExpansion interface{}

// SecretExportListerExpansion allows custom methods to be added to
// SecretExportLister.
type SecretExportListerExpansion interface{}

// SecretExportNamespaceListerExpansion allows custom methods to be added to
// SecretExportNamespaceLister.
type SecretExportNamespaceListerExpansion interface{}

// SecretRequestListerExpansion allows custom methods to be added to
// SecretRequestLister.
type SecretRequestListerExpansion interface{}

// SecretRequestNamespaceListerExpansion allows custom methods to be added to
// SecretRequestNamespaceLister.
type SecretRequestNamespaceListerExpansion interface{}
